apiVersion: v1
kind: Service
metadata:
  name: worktime-web
  namespace: worktime
spec:
  type: ClusterIP
  selector:
    app: worktime-web
  ports:
    - name: http
      port: 80
      targetPort: http
